import type { Assignment } from '@/types'

export const MOCK_ASSIGNMENTS: (Assignment & { likes: number })[] = [
  {
    id: '1',
    title: '소비자행동론 기말 보고서 - 명품 구매의사결정 분석',
    school: '연세대학교',
    department: '경영학과',
    subject: '소비자행동론',
    professor: '이현수 교수',
    grade: '상',
    description: null,
    file_url: '',
    transcript_url: '',
    has_professor_feedback: true,
    point_cost: 10,
    download_count: 142,
    is_verified: true,
    is_published: true,
    uploader_id: 'mock-1',
    created_at: '2025-03-01',
    likes: 89,
  },
  {
    id: '2',
    title: '자료구조 과제 3 - 이진탐색트리 구현 및 분석',
    school: '고려대학교',
    department: '컴퓨터공학과',
    subject: '자료구조',
    professor: '박재현 교수',
    grade: '상',
    description: null,
    file_url: '',
    transcript_url: '',
    has_professor_feedback: false,
    point_cost: 10,
    download_count: 98,
    is_verified: true,
    is_published: true,
    uploader_id: 'mock-2',
    created_at: '2025-03-05',
    likes: 63,
  },
  {
    id: '3',
    title: '거시경제학 중간고사 레포트 - 인플레이션과 통화정책',
    school: '서울대학교',
    department: '경제학과',
    subject: '거시경제학',
    professor: '김민정 교수',
    grade: '중상',
    description: null,
    file_url: '',
    transcript_url: '',
    has_professor_feedback: false,
    point_cost: 10,
    download_count: 77,
    is_verified: true,
    is_published: true,
    uploader_id: 'mock-3',
    created_at: '2025-03-10',
    likes: 45,
  },
  {
    id: '4',
    title: '사회심리학 팀 프로젝트 - SNS가 청년 자존감에 미치는 영향',
    school: '성균관대학교',
    department: '심리학과',
    subject: '사회심리학',
    professor: '최지연 교수',
    grade: '상',
    description: null,
    file_url: '',
    transcript_url: '',
    has_professor_feedback: true,
    point_cost: 10,
    download_count: 63,
    is_verified: true,
    is_published: true,
    uploader_id: 'mock-4',
    created_at: '2025-03-12',
    likes: 38,
  },
  {
    id: '5',
    title: '회귀분석 최종 프로젝트 - 서울 아파트 가격 예측 모델',
    school: '한양대학교',
    department: '통계학과',
    subject: '회귀분석',
    professor: '정태훈 교수',
    grade: '중상',
    description: null,
    file_url: '',
    transcript_url: '',
    has_professor_feedback: false,
    point_cost: 10,
    download_count: 55,
    is_verified: true,
    is_published: true,
    uploader_id: 'mock-5',
    created_at: '2025-03-15',
    likes: 31,
  },
  {
    id: '6',
    title: '영문학 세미나 - 셰익스피어 햄릿의 현대적 해석',
    school: '연세대학교',
    department: '영어영문학과',
    subject: '영문학세미나',
    professor: 'Sarah Kim 교수',
    grade: '중',
    description: null,
    file_url: '',
    transcript_url: '',
    has_professor_feedback: false,
    point_cost: 10,
    download_count: 34,
    is_verified: false,
    is_published: true,
    uploader_id: 'mock-6',
    created_at: '2025-03-20',
    likes: 22,
  },
]

export const DEPARTMENTS = ['경영학과', '컴퓨터공학과', '경제학과', '심리학과', '통계학과', '영어영문학과']
